### Sikit-Learn 라이브러리
- 머신러닝을 다루는 다양한 라이브러리가 있습니다.
- Tensorflow, Keras, Pytorch, Sikit-learn

In [2]:
%pip install scikit-learn

  Using cached scipy-1.14.1-cp313-cp313-macosx_14_0_x86_64.whl.metadata (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 44.9 MB/s eta 0:00:00 0:00:01
Using cached scipy-1.14.1-cp313-cp313-macosx_14_0_x86_64.whl (25.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
import sklearn
print(sklearn.__version__)

1.6.0


In [8]:
# Classification - 분류 알고리즘을 사용해서 꽃의 종류를 구분하기
from sklearn.datasets import load_iris
import pandas as pd

In [10]:
iris = load_iris()

iris.data # feature data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris.target # lable data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
# 1. 준비되어있는 데이터셋을 나눈다.
# (1). 학습용 데이터(train_data)
# (2). 테스트용 데이터(test_data)

# train_test_split() -> 학습용 데이터셋과 테스트용 셋으로 분리하는 역할
from sklearn.model_selection import train_test_split

# X_train : 학습용 피처 데이터, X_test : 테스트용 피처 데이터
# y_train : 학습용 레이블 데이터, y_test : 테스트용 레이블 데이터

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 101)
# random_status => 이 숫자가 갖는 의미는 없지만 숫자를 고정시키는데에 의미가 있다

In [16]:
y_test
len(y_train)

120

In [17]:
# 2. 학습을 위한 알고리즘을 불러옵니다.
from sklearn.tree import DecisionTreeClassifier # 분류 알고리즘 (supervised learning)

dt_clf = DecisionTreeClassifier(random_state = 101)
dt_clf

DecisionTreeClassifier(random_state=101)

In [18]:
# 3. 학습을 진행합니다. => train_data 사용 (X_train, y_train) // 모으고사
dt_clf.fit(X_train, y_train) # fit() : 학습을 진행한다

DecisionTreeClassifier(random_state=101)

In [19]:
# 4. 시험을 치러 갑니다. => test_data(X_test, y_test) // 수능시험
# predict() : 예측해봐
predict = dt_clf.predict(X_test)
predict

array([0, 0, 0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0])

In [22]:
# 5. 채점을 진행합니다.
# accuracy_score()

from sklearn.metrics import accuracy_score
accuracy_score(y_test, predict)

0.9666666666666667

In [24]:
df = pd.DataFrame(data = X_test, columns = iris.feature_names)

df['answer'] = y_test
df['predict'] = predict

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.5               4.2                1.4               0.2   
1                 5.4               3.9                1.3               0.4   
2                 5.0               3.5                1.6               0.6   
3                 7.2               3.0                5.8               1.6   
4                 7.0               3.2                4.7               1.4   
5                 6.3               2.7                4.9               1.8   
6                 6.2               2.2                4.5               1.5   
7                 5.5               2.3                4.0               1.3   
8                 6.3               2.5                5.0               1.9   
9                 4.9               3.0                1.4               0.2   
10                6.5               3.0                5.2               2.0   
11                5.2               4.1                1.5               0.1   
12                5.4               3.4                1.5               0.4   
13                7.7               2.8                6.7               2.0   
14                6.1               3.0                4.9               1.8   
15                6.4               2.9                4.3               1.3   
16                5.6               3.0                4.1               1.3   
17                5.7               2.9                4.2               1.3   
18                4.4               3.2                1.3               0.2   
19                6.1               2.6                5.6               1.4   
20                5.5               2.4                3.8               1.1   
21                5.3               3.7                1.5               0.2   
22                5.5               2.6                4.4               1.2   
23                6.7               3.1                4.4               1.4   
24                6.2               2.9                4.3               1.3   
25                5.6               2.9                3.6               1.3   
26                5.0               2.3                3.3               1.0   
27                5.8               2.8                5.1               2.4   
28                5.0               3.0                1.6               0.2   
29                4.5               2.3                1.3               0.3   

    answer  predict  
0        0        0  
1        0        0  
2        0        0  
3        2        1  
4        1        1  
5        2        2  
6        1        1  
7        1        1  
8        2        2  
9        0        0  
10       2        2  
11       0        0  
12       0        0  
13       2        2  
14       2        2  
15       1        1  
16       1        1  
17       1        1  
18       0        0  
19       2        2  
20       1        1  
21       0        0  
22       1        1  
23       1        1  
24       1        1  
25       1        1  
26       1        1  
27       2        2  
28       0        0  
29       0        0

In [26]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
dt_clf.fit(iris.data, iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target, pred)

1.0

## 교차 검증
- (1) K Fold 검증
- (2) Stratified 검증
- (3) cross_val_score()=> 검증을 쉽게 할 수 있도록 도와주는 함수

In [28]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [29]:
# 데이터 로드
iris = load_iris()
train_data = iris.data
train_target = iris.target

In [30]:
# 모델 학습 및 평가 함수 정의
def train_and_evaluate(train_index, test_index, model, train_data, train_target):
    # 학습 및 검증 데이터 분리
    X_train, X_test = train_data[train_index], train_data[test_index]
    y_train, y_test = train_target[train_index], train_target[test_index]

    # 모델 학습 및 예측
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(y_test, predictions)
    return accuracy, X_train.shape[0], X_test.shape[0], test_index

In [31]:
# KFold 교차 검증 설정
kfold = KFold(n_splits=5)
cv_accuracy = []
dt_clf = DecisionTreeClassifier()

In [32]:
# KFold 교차 검증 수행
for fold, (train_index, test_index) in enumerate(kfold.split(train_data), 1):
    accuracy, train_size, test_size, test_idx = train_and_evaluate(
        train_index, test_index, dt_clf, train_data, train_target
    )
    cv_accuracy.append(accuracy)


    print(f"{fold}번째 트레이닝")
    print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"검증 데이터 셋 인덱스 값: {test_idx}")
    print(f"===" * 10)

# 최종 정확도 평균 출력
print("최종 정확도 평균 값: ", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2번째 트레이닝
검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3번째 트레이닝
검증 정확도: 0.8333333333333334, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4번째 트레이닝
검증 정확도: 0.9333333333333333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5번째 트레이닝
검증 정확도: 0.7666666666666667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
최종 정확도 평균 값:  0.9066666666666666


In [33]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# iris 데이터 셋 로드
iris = load_iris()
features = iris.data
label = iris.target

# 모델 초기화
dt_clf = DecisionTreeClassifier(random_state=156)

# Stratified KFold 교차 검증 설정
skfold = StratifiedKFold(n_splits=3)
cv_accuracy = []

# Stratified KFold 교차 검증 수행

for fold, (train_index, test_index) in enumerate(skfold.split(features, label), 1):
    accuracy, train_size, test_size, test_idx = train_and_evaluate(
        train_index, test_index, dt_clf, features, label
    )
    cv_accuracy.append(accuracy)

    # 출력 메세지 변경
    print(f"{fold}번째 트레이닝")
    print(f"검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"검증 데이터 셋 인덱스 값: {test_idx}")
    print("===" * 10)

# 교차 검증 별 정확도 및 평균 정확도 계산
print("\n최종 정확도 평균 값:", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2번째 트레이닝
검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3번째 트레이닝
검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

최종 정확도 평균 값: 0.9666666666666667


In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf, data, label, scoring="accuracy", cv=5)

print("교차 검증 별 정확도: ", np.round(scores, 5))
print("평균 검증 정확도: ", np.round(np.mean(scores), 5))

교차 검증 별 정확도:  [0.96667 0.96667 0.9     0.96667 1.     ]
평균 검증 정확도:  0.96


### 데이터 인코딩
- (1) Label Encoding
- (2) OneHot Encoding
- (3) GetDeummies - pd 의 df 를 활용한 방법

In [35]:
from sklearn.preprocessing import LabelEncoder

items = ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]

# LabelEncoder 를 객체로 생성한 후, fit() 와 transform() 으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값 : ", labels) # 문자열 값 -> 숫자형 값으로 변경 (Label Encoding)

인코딩 변환값 :  [0 3 4 1 2 2 5 5]


In [36]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]

# 2차원 ndarray 로 변환합니다
# reshape() 함수의 첫 번째 인자로 -1 을 주면 해당 차원의 크기를 자동으로 계산하여 맞춰줍니다
# 두 번째 인자로 1 을 주면 열의 크기를 1 로 지정하여 결과적으로 1개의 열로 이루어진 2차원 배열을 생성합니다
# 이렇게 2차원 배열로 변환된 데이터는 머신 러닝 모델에 입력으로 사용하기에 적합한 형태가 됩니다
# 머신 러닝 모델은 입력으로 2차원 배열을 기대하므로, 데이터를 이와 같은 형태로 변환하여 모델에 사용해야 합니다

items = np.array(items).reshape(-1, 1)

# 원-핫 인코딩을 적용합니다
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder 로 변환한 결과는 희소행렬 (Sparse Matrix) 이므로 toarray() 를 이용하여 밀집 행렬 (Dense Matrix) 로 변환
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [37]:
# df.get_dummies()
import pandas as pd
df = pd.DataFrame({"item" : ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]})

pd.get_dummies(df)

item_강남구  item_노원구  item_마포구  item_서초구  item_송파구  item_용산구
0      True     False     False     False     False     False
1     False     False     False      True     False     False
2     False     False     False     False      True     False
3     False      True     False     False     False     False
4     False     False      True     False     False     False
5     False     False      True     False     False     False
6     False     False     False     False     False      True
7     False     False     False     False     False      True

In [38]:
import pandas as pd

data = {
    "Fruit" : ["Apple", "Banana", "Cherry", "Apple", "Cherry"],
    "Color" : ["Red", "Yellow", "Red", "Green", "Red"]
}
df = pd.DataFrame(data)
df # 이 상태에서는 모델링이 어렵지만

Fruit   Color
0   Apple     Red
1  Banana  Yellow
2  Cherry     Red
3   Apple   Green
4  Cherry     Red

In [39]:
pd.get_dummies(df) # 이 상태에서는 학습이 이루어짐

Fruit_Apple  Fruit_Banana  Fruit_Cherry  Color_Green  Color_Red  \
0         True         False         False        False       True   
1        False          True         False        False      False   
2        False         False          True        False       True   
3         True         False         False         True      False   
4        False         False          True        False       True   

   Color_Yellow  
0         False  
1          True  
2         False  
3         False  
4         False